kitty-review!!!!!!!!!!!!!!!!!!!!
SSPS-KB/workshop-bot pull request #13
Opened 2023-02-16 19:53 UTC by petulkauwu

Treba jsem tupej, a toto nefakci. 

Kazdopadne, udelej si API key na gify.

2023-02-16 20:50 UTC, marekvospel requested changes

2023-02-16 20:50 UTC, marekvospel commented on src/commands/kitty-review.rs
> +                            if let Some(gif) = first_media.get("gif").and_then(|gif| gif.get("url").and_then(|url| url.as_str())) {
Unnecessary to do so many json operations and Option checks, It's smarter to create a struct (with Serialize and Deserialize derive) and check whether the custom result output was parsed successfully.

https://serde.rs/derive.html
See also /src/state/config.rs

2023-02-16 20:50 UTC, marekvospel commented on src/commands/kitty-review.rs
> +    let tenor_api_key = "API KEY ZDE";
API KEY should NEVER be part of your source code, you can either use environment or use the config object (see how discord_token is loaded from Config.toml)

2023-02-16 20:50 UTC, marekvospel commented on src/commands/kitty-review.rs
> +        .header(header::USER_AGENT, "SSPS-KB BOT")
`User-Agent: <product> / <product-version> <comment>`
```suggestion
        .header(header::USER_AGENT, "SSPS-KB/1.0 workshop-bot")
```

2023-02-16 20:50 UTC, marekvospel commented on src/commands/kitty-review.rs
> +        .await;
This code should be in a separate function, so it can be reused.

2023-02-16 20:50 UTC, marekvospel commented on src/commands/kitty-review.rs
> +                                return;
unnecessary return

2023-02-16 20:50 UTC, marekvospel commented on src/commands/kitty-review.rs
> +        }
No error log

2023-02-16 21:03 UTC, marekvospel commented
Also please create a change file inside .changes directory

2023-02-16 21:05 UTC, petulkauwu commented
moje rust skills above

2023-02-16 21:05 UTC, petulkauwu commented
taky brainless code

2023-02-17 20:10 UTC, marekvospel commented
@petulkauwu I need you to actually do the requested changes, not just click resolve

2023-02-17 21:44 UTC, petulkauwu commented
ono se to a me to napsalo ze se to samo commitne :(

2023-02-17 21:44 UTC, petulkauwu commented
udělám pak novy

2023-02-17 21:44 UTC, closed without merging

2023-02-17 21:44 UTC, petulkauwu commented
very real!!!!!